config/routes.rb
MovercadoAnalysis::Application.routes.draw do
  get "kannel/entry_point"
  get "activista_summary" => "users#activista_summary", :as => :activista_summary

  resources :codes

  resources :apps
  resources :troca_aki_validations, :controller => "apps", :type => "TrocaAkiValidation"
  resources :ipc_validations, :controller => "apps", :type => "IpcValidation"

  resources :users

  root to: "smses#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :roles
  has_many :interactions
  has_many :codes
  has_many :phones

  attr_accessible :roles_attributes, :phones_attributes

  accepts_nested_attributes_for :roles, :phones

  # Scopes
  scope :activistas, joins(:roles).where("roles.name = 'activista'") # Returns all activistas
  scope :vendors, joins(:roles).where("roles.name = 'vendor'") # Returns all activistas

  def default_phone
    (phones.blank?) ? Phone.create(number: SecureRandom.hex) : phones.first
  end

  def interacted?(app)
    self.interactions.where(app_id: app.id).present?
  end

  def vendor?(app)
    has_role?(app, "vendor")
  end

  def activista?(app)
    has_role?(app, "activista")
  end

  def has_role?(app, role_name)
    self.roles.where(app_id: app.id, name: role_name).present?
  end

  def to_s
    "#{self.id}"
  end

  def self.top_activistas(week=Date.today.beginning_of_week)
    activistas_interactions = self.activistas.joins(:interactions).group("users.id").where("interactions.created_at" => week..week.end_of_week).count
    Hash[activistas_interactions.sort_by { |user_id, interactions_count| interactions_count }.reverse[0..9]]
  end

  def sessions_count_in(week=Date.today.beginning_of_week)
    self.interactions.where("interactions.created_at" => week..week.end_of_week).count
  end

  def first_session_in(week=Date.today.beginning_of_week)
    self.interactions.where("interactions.created_at" => week..week.end_of_week).order("created_at DESC").first
  end

  def last_session_in(week=Date.today.beginning_of_week)
    self.interactions.where("interactions.created_at" => week..week.end_of_week).order("created_at ASC").first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  # GET /activista_summary
  # GET /activista_summary.json
  def activista_summary
    @week = params[:week].present? ? Time.parse(params[:week]) : Date.today.beginning_of_week
    @activistas = User.top_activistas(@week)

    respond_to do |format|
      format.html
      format.json { render json:@activistas }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_nested_form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h4>Roles</h4>
  <%= f.simple_fields_for :roles do |role_form| %>
    <%= role_form.input :app_id, collection: App.all, value_method: :id, label_method: :name %>
    <%= role_form.input :name, collection: Role.all.uniq { |r| r.name }, value_method: :name, label_method: :name %>
    <%= role_form.link_to_remove "Remove role" %>
  <% end %>
  <%= f.link_to_add "Add role for user", :roles %>

  <h4>Phones</h4>
  <%= f.simple_fields_for :phones do |phone_form| %>
    <%= phone_form.input :number %>
    <%= phone_form.link_to_remove "Remove phone" %>
  <% end %>
  <%= f.link_to_add "Add phone for user", :phones %>

  <%= render 'interactions/index', user: @user %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/activista_summary.html.erb
<h1>Top Activistas</h1>

<%= link_to '< Previous week', activista_summary_path(:week => @week.advance(:weeks => -1).to_date) %>
<%= link_to 'Next week >', activista_summary_path(:week => @week.advance(:weeks => 1).to_date) %>


<table>
  <tr>
    <th>ID</th>
    <th># of sessions</th>
    <th>Time of first session</th>
    <th>Time of last session</th>
  </tr>

<% @activistas.each do |activista_id, sessions_count| %>
  <tr>
    <td><%= activista_id %></td>
    <td><%= sessions_count %></td>
    <td><%= User.find(activista_id).first_session_in.created_at %></td>
    <td><%= User.find(activista_id).last_session_in.created_at %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<%= link_to 'New User', new_user_path %>

<table>
  <tr>
    <th>ID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>