config/routes.rb
MovercadoAnalysis::Application.routes.draw do
  get "kannel/entry_point"
  get "activista_summary" => "users#activista_summary", :as => :activista_summary

  resources :codes

  resources :apps
  resources :troca_aki_validations, :controller => "apps", :type => "TrocaAkiValidation"
  resources :ipc_validations, :controller => "apps", :type => "IpcValidation"

  resources :users

  root to: "smses#index"

end

app/models/code.rb
class Code < ActiveRecord::Base
  belongs_to :user
  belongs_to :app
  attr_accessible :code, :user_id, :app_id

  before_create :fill_code

  def inc_usage
    self.times_used += 1
    self.save
  end

  def self.gen
    code = ""
    6.times do
      r = rand(36)
      if r >= 10
        c = (55+r).chr
      else
        c = r.to_s
      end
      code << c
    end
    code = Sms.replace_ambig_characters(code.downcase)
    if Code.find_by_code(code)
      generate_code
    else
      return code.downcase
    end
  end

  def to_s
    "#{app.code}#{code}".upcase
  end

  def fill_code
    self.code ||= Code.gen
  end
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  # GET /codes
  # GET /codes.json
  def index
    @codes = Code.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @codes }
    end
  end

  # GET /codes/1
  # GET /codes/1.json
  def show
    @code = Code.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @code }
    end
  end

  # GET /codes/new
  # GET /codes/new.json
  def new
    @code = Code.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @code }
    end
  end

  # GET /codes/1/edit
  def edit
    @code = Code.find(params[:id])
  end

  # POST /codes
  # POST /codes.json
  def create
    @code = Code.new(params[:code])

    respond_to do |format|
      if @code.save
        format.html { redirect_to @code, notice: 'Code was successfully created.' }
        format.json { render json: @code, status: :created, location: @code }
      else
        format.html { render action: "new" }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /codes/1
  # PUT /codes/1.json
  def update
    @code = Code.find(params[:id])

    respond_to do |format|
      if @code.update_attributes(params[:code])
        format.html { redirect_to @code, notice: 'Code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /codes/1
  # DELETE /codes/1.json
  def destroy
    @code = Code.find(params[:id])
    @code.destroy

    respond_to do |format|
      format.html { redirect_to codes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/views/codes/_form.html.erb
<%= form_for(@code) do |f| %>
  <% if @code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@code.errors.count, "error") %> prohibited this code from being saved:</h2>

      <ul>
      <% @code.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.collection_select :user_id, User.all, :id, :id %>
  </div>
  <div class="field">
    <%= f.label :app %><br />
    <%= f.collection_select :app_id, App.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/codes/edit.html.erb
<h1>Editing code</h1>

<%= render 'form' %>

<%= link_to 'Show', @code %> |
<%= link_to 'Back', codes_path %>

app/views/codes/index.html.erb
<h1>Listing codes</h1>

<table>
  <tr>
    <th>Printable</th>
    <th>User</th>
    <th>App</th>
    <th>Code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @codes.each do |code| %>
  <tr>
    <td><b><%= code.to_s %></b></td>
    <td><%= code.user %></td>
    <td><%= code.app %></td>
    <td><%= code.code %></td>
    <td><%= link_to 'Show', code %></td>
    <td><%= link_to 'Edit', edit_code_path(code) %></td>
    <td><%= link_to 'Destroy', code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Code', new_code_path %>

app/views/codes/new.html.erb
<h1>New code</h1>

<%= render 'form' %>

<%= link_to 'Back', codes_path %>

app/views/codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @code.user %>
</p>

<p>
  <b>App:</b>
  <%= @code.app %>
</p>

<p>
  <b>Code:</b>
  <%= @code.to_s %>
</p>


<%= link_to 'Edit', edit_code_path(@code) %> |
<%= link_to 'Back', codes_path %>